#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: launchpads

on:
  push:
    branches-ignore:
        - master

env:
  #Terraform Auth
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  integration-tests:
    name: Execute from launchpad ${{ matrix.launchpad }} in region ${{ matrix.region }} with arguments ${{ matrix.arguments }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        launchpad: ["launchpad_opensource_light"]
        region: ["southeastasia"]
        arguments: [""]

    steps:
      - uses: actions/checkout@v2

      - name: Login registry
        uses: azure/docker-login@v1
        with:
          username: '${{ secrets.DOCKER_USER }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'

      - name: Pull rover  
        uses: ./.github/workflows/action
        with:
          entrypoint: /bin/bash
          args: "az login --service-principal -u "${{ env.ARM_CLIENT_ID }}" -p "${{ env.ARM_CLIENT_SECRET }}" --tenant "${{ env.ARM_TENANT_ID }}" && \
            az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }} && \ 
            /tf/rover/rover.sh /tf/caf/launchpads/launchpad_opensource_light plan"

      # - name: Execute deployment
      #   run: |
      #     az login --service-principal -u "${{ env.ARM_CLIENT_ID }}" -p "${{ env.ARM_CLIENT_SECRET }}" --tenant "${{ env.ARM_TENANT_ID }}"
      #     az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}
      #     echo $(pwd)
      #     ls -lsa

      #     echo "ls /" && ls -lsa /
      #     echo "ls /tf" && ls -lsa /tf
      #     echo "ls /tf/rover" && ls -lsa /tf/rover

      #     /tf/rover/launchpad.sh /tf/launchpads/${{ matrix.launchpad}} plan -var location=${{ matrix.region}} ${{ matrix.arguments }}
      #     /tf/rover/launchpad.sh /tf/launchpads/${{ matrix.launchpad}} apply -var location=${{ matrix.region}} ${{ matrix.arguments }}
      #     /tf/rover/launchpad.sh /tf/launchpads/${{ matrix.launchpad}} destroy -var location=${{ matrix.region}} ${{ matrix.arguments }} -auto-approve
