#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: launchpads

on:
  push:
    branches-ignore:
        - master

env:
  #Terraform Auth
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  integration-tests:
    name: Execute terraform ${{ matrix.tf_command }} in region ${{ matrix.region }} with arguments ${{ matrix.arguments }}
    runs-on: ubuntu-latest

    container:
      image: 'aztfmod/rover:2003.2011'
      options: --user 0

    
    strategy:
      matrix:
        region: ["southeastasia"]
        tf_command: ["plan"]
        arguments: [""]
    steps:
      - uses: actions/checkout@v2
      - name: Login Azure subscription
        run: |
          az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant  ${{ secrets.ARM_TENANT_ID }}
          az account set -s ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Terraform ${{ matrix.tf_command }}
        run: |
          ls -lsa
          # ./rover/launchpad.sh /tf/launchpads/launchpad_opensource_light ${{ matrix.tf_command }} -var location=${{ matrix.region}} ${{ matrix.arguments }}
          /tf/rover/launchpad.sh
