#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: launchpads

on:
  push:
    branches-ignore:
        - master

env:
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_azure_devops_pat_token: ${{ secrets.TF_VAR_azure_devops_pat_token }}
  TF_VAR_azure_devops_url_organization: ${{ secrets.TF_VAR_azure_devops_url_organization }}

jobs:
  level0:
    name: level0
    runs-on: ubuntu-latest
    
    container:
      image: aztfmod/rover:2004.0813
      options: --user 0

    steps:
      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
      
      - name: Locate launchpad
        run: |
         id=$(az storage account list --query "[?tags.tfstate=='level0']" | jq -r .[0].id)
          if [ "${id}" == "null" ]; then
            /tf/rover/launchpad.sh /tf/launchpads/launchpad_opensource plan -var location=${{ matrix.region }}
            /tf/rover/launchpad.sh /tf/launchpads/launchpad_opensource apply -var location=${{ matrix.region }}
          fi

  launchpad:
    name: Launchpad tests
    runs-on: ubuntu-latest
    
    needs: level0

    strategy:
      fail-fast: true
      matrix:
        launchpad: ["launchpad_opensource_light", "launchpad_opensource"]
        region: ["westus2"]
        arguments: ["'-var convention=cafclassic'"]
    
    container:
      image: aztfmod/rover:2004.0813
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        run: |
          ln -s /__w/level0/level0 /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
      
      - name: Terraform plan
        run: |
          /tf/rover/rover.sh /tf/caf/launchpads/${{ matrix.launchpad }} plan \
              '-var location=${{ matrix.region }}' \
              '-var tags={testing-job-id="${{ github.run_id }}"}' \
              ${{ matrix.arguments }}

      - name: Terraform apply
        run: |
          /tf/rover/rover.sh /tf/caf/launchpads/${{ matrix.launchpad }} apply \
              '-var location=${{ matrix.region }}' \
              '-var tags={testing-job-id="${{ github.run_id }}"}' \
              ${{ matrix.arguments }}

      - name: Terraform destroy
        run: |
          /tf/rover/rover.sh /tf/caf/launchpads/${{ matrix.launchpad }} destroy \
              '-var location=${{ matrix.region }}' \
              '-var tags={testing-job-id="${{ github.run_id }}"}' \
              ${{ matrix.arguments }} \
              -auto-approve
