#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: launchpads

on:
  push:
    branches-ignore:
        - master

env:
  #Terraform Auth
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_azure_devops_pat_token: ${{ secrets.TF_VAR_azure_devops_pat_token }}
  TF_VAR_azure_devops_url_organization: ${{ secrets.TF_VAR_azure_devops_url_organization }}

jobs:
  launchpad:
    name: Launchpad tests
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        launchpad: ["launchpad_opensource_light", "launchpad_opensource"]
        region: ["southeastasia"]
        arguments: ["'-var convention=cafclassic'"]
    
    steps:
      - uses: actions/checkout@v2

      - name: Login azure
        run: |
          docker run --rm -v /home/runner/work/level0/level0:/tf/caf -v volume-caf-vscode:/home/vscode aztfmod/roverdev:2004.060747  az account show
          # az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          # echo "local user: $(whoami)"

          